version: '3'

services:

  alpine:
    image: alpine:latest
    stdin_open: true
    tty: true
    environment:
     - wup=hoopla
     - krabby=patty
    volumes:
     - ./html:/home/folder
