version: '3'
services:
 app:
  image: ${IMAGE:-nats}
  tty: ${BOOLEAN:-false}
  stdin_open: ${BOOLEAN:-false}
  ports:
   - ${PORTS:-81}:80
  environment:
   - ${ENV:-environment}=deck
   - ${ENV2:-environment2}=ally
   - ${ENV3:-environment3}=mnn
   - ${ENV4:-environment4}=dasd

