version: '3'
services:
 app:
  image: ${IMAGE:-nats}
  tty: ${BOOLEAN:-false}
  stdin_open: ${BOOLEAN:-false}
  environment:
   - ${ENV1:-environment1}=deck
   - ${ENV2:-environment2}=ally
  ports:
   - 80:80


