version: '3'

services:
  nginx-app:
    image: ${IMAGE2:-nginx}
    tty: ${BOOLEAN:-false}
    stdin_open: ${BOOLEAN:-false}
    environment:
     - banana=berries
     - ${ENV:-shrek}=${EATER:-rum}
     - ${ENV2:-borrito}=wallet
     - get=shinji

