version: '3'

services:

  nginx:
    image: ${IMAGE:-nginx}
    tty: true
    stdin_open: true
    environment:
     - banana=berries
     - ${SNAKE:-shrek}=${EATER:-rum}
     - ${IMAGE:-borrito}=wallet
    ports:
     - ${PORT:-8080}:80
