version: '3'
services:
 nats:
  image: natsasddjfl;kdsfjslfjsadlk;fjklfjsaalkfjslkfjsdklfjsdlkfsfsdfkjdsafjksadhfksjdfhsdjfhasjdhadkfhasjfhdfhfjkdsfhsjadfhdskfjhasfjksdhfjdshfdskjfhsdkfjhsdafhsadfdklhlkdjasfhdklsfhsakldfhldsfhsdfhsjfhdjfhdsjkfhjsdkfhsjfhsjfhsdjfhsjfhasdjfhasdfhasjfhaskjfhsdjfhdjfsahfjshfsajkfhaskjfhlsfsdfsdfsadfsdfsdafsafsadfasdfsadf
