version: '3'
services:
 aws:
  image: 090831636769.dkr.ecr.us-east-1.amazonaws.com/private:nats
  tty: true
  stdin_open: true
  ports:
   - "8080:8080"
  volumes:
   - ../README.md:/web/README.md
  environment:
   - aws=updateviawebhook
