apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - name: alpine
    image: alpine:latest
    stdin: true 
    tty: true 

#To attach use microk8s kubectl exec --tty --stdin pod/name -- /bin/ash

