apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - name: alpine
    image: 6261998/alpine:latest
    stdin: true 
    tty: true 
    env:
     - name: hello
       value: hoop

#To attach use microk8s kubectl exec --tty --stdin pod/name -- /bin/ash

