apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-with-resource
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 80
        resources:
         limits:
          cpu: "0.1"
          memory: "100Mi"
